### ISSUE TITLE
Problème de cookie

### ISSUE THREAD

**Issue by mbelang** [mlemelin/xbmc-illicowebtv#9]
Le plugin ne load pas et j'ai cette erreur dans les logs:

```
0-10-02 17:32:49.857 T:1504969600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.video.illicoweb/cookie'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.illicoweb/default.py", line 25, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/plugin.video.illicoweb/resources/lib/illicoweb.py", line 296, in __init__
                                                if (not sessionCheck()):
                                              File "/storage/.kodi/addons/plugin.video.illicoweb/resources/lib/illicoweb.py", line 124, in sessionCheck
                                                c.cookies.save(ignore_discard=True)
                                              File "/usr/lib/python2.7/_LWPCookieJar.py", line 83, in save
                                            IOError: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.video.illicoweb/cookie'
                                            -->End of Python script error report<--
```

**Comment by mbelang** [comment]
Je viens de voir que dans userdata je n'ai pas le plugin settings.xml.

Je suis sur libreelec
